
/*
---------------------------------------
Generated by:NITIN KUMAR
Inst. name:ASET BIJWASEN
-----------------------------------------
*/
#include <iostream>
using namespace std;

int main()
{
	int n;
	cin>>n;
	static int j=1;
	for (int i = 0; i < n; i++) 
	{
	    if(i==j)
	    {
	        cout<<"\n";
	        j++;
	        i=0;
	    }
		cout<<"*";
	}
	return 0;
}
/*
*
**
***
****
*****
******
*/
